- ros_topic_name: "/clock"
  gz_topic_name: "/world/eddie_world/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/eddie/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "odom"
  gz_topic_name: "/model/eddie/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: "GZ_TO_ROS"
- ros_topic_name: "imu"
  gz_topic_name: "/eddie_imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
# Laser scan topics
- ros_topic_name: "scan"
  gz_topic_name: "/eddie_front_right_laser"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
# - ros_topic_name: "scan"
#   gz_topic_name: "/eddie_rear_left_laser"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: GZ_TO_ROS
# odom to base_footprint transform
- ros_topic_name: "/tf"
  gz_topic_name: "/model/eddie/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
