name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/ci_dep.repos"
          package-name: kortex_description robotiq_description eddie_description eddie_gazebo
